<?php
/**
 * For operating items in functions-custom-0.php and functions-custom-1.php
 * $hui_item_content: an array of the item's info
 * return TRUE or FALSE
 */
class hui_item_operator{
    var $hui_target_file_name;

    function __construct($hui_functions_file_name){
        $this -> hui_target_file_name = 'custom/'.$hui_functions_file_name;
    }

    public function add_item($hui_item_content){
        //...
    }

    public function edit_item($hui_item_id, $hui_item_content){
        //...
    }

    public function delete_item($hui_item_id){
        //...
    }

    public function delete_all_items(){
        $file = fopen($this -> hui_target_file_name, "w") or die("Unable to open the file");
        if($this -> hui_target_file_name === "custom/functions-custom-0.php"){
            $group = "1";
        }else if($this -> hui_target_file_name === "custom/functions-custom-1.php"){
            $group = "2";
        }else{
            return false;
        }
        $content = "<?php\n/**\n * All custom hooks here\n * Hooks group ".$group."\n * DO NOT EDIT THIS FILE MANUALLY!\n * Last automatical change: ".date('Y-m-d H:i:s')."\n */\n\n\n?>";
        fwrite($file, $content);
        fclose($file);
        return true;
    }

    public function disable_item($hui_item_id){
        //...
    }

    public function disable_all_items(){
        //...
    }

    public function enable_item($hui_item_id){
        //...
    }

    public function enable_all_items(){
        //...
    }
}
?>